

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:amenity-reservation-system}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #CheckEmail
  mail:
    host: mail.gmx.com
    port: 587
    username: aqua.aqua@gmx.com
    password: adminAqua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
springdoc:
  pathsToMatch: /api/**
